/**
 * Country flag utilities
 * Maps country names to their corresponding flag emojis
 * Based on ISO 3166-1 alpha-2 country codes
 */

const COUNTRY_FLAGS: Record<string, string> = {
  // Major countries
  'afghanistan': '🇦🇫',
  'albania': '🇦🇱',
  'algeria': '🇩🇿',
  'argentina': '🇦🇷',
  'armenia': '🇦🇲',
  'australia': '🇦🇺',
  'austria': '🇦🇹',
  'azerbaijan': '🇦🇿',
  'bangladesh': '🇧🇩',
  'belarus': '🇧🇾',
  'belgium': '🇧🇪',
  'brazil': '🇧🇷',
  'bulgaria': '🇧🇬',
  'cambodia': '🇰🇭',
  'canada': '🇨🇦',
  'chile': '🇨🇱',
  'china': '🇨🇳',
  'colombia': '🇨🇴',
  'croatia': '🇭🇷',
  'czech-republic': '🇨🇿',
  'denmark': '🇩🇰',
  'egypt': '🇪🇬',
  'estonia': '🇪🇪',
  'finland': '🇫🇮',
  'france': '🇫🇷',
  'georgia': '🇬🇪',
  'germany': '🇩🇪',
  'ghana': '🇬🇭',
  'greece': '🇬🇷',
  'hungary': '🇭🇺',
  'iceland': '🇮🇸',
  'india': '🇮🇳',
  'indonesia': '🇮🇩',
  'iran': '🇮🇷',
  'iraq': '🇮🇶',
  'ireland': '🇮🇪',
  'israel': '🇮🇱',
  'italy': '🇮🇹',
  'japan': '🇯🇵',
  'jordan': '🇯🇴',
  'kazakhstan': '🇰🇿',
  'kenya': '🇰🇪',
  'south-korea': '🇰🇷',
  'kuwait': '🇰🇼',
  'latvia': '🇱🇻',
  'lebanon': '🇱🇧',
  'lithuania': '🇱🇹',
  'luxembourg': '🇱🇺',
  'malaysia': '🇲🇾',
  'mexico': '🇲🇽',
  'moldova': '🇲🇩',
  'mongolia': '🇲🇳',
  'morocco': '🇲🇦',
  'myanmar': '🇲🇲',
  'nepal': '🇳🇵',
  'netherlands': '🇳🇱',
  'new-zealand': '🇳🇿',
  'nigeria': '🇳🇬',
  'north-korea': '🇰🇵',
  'norway': '🇳🇴',
  'pakistan': '🇵🇰',
  'peru': '🇵🇪',
  'philippines': '🇵🇭',
  'poland': '🇵🇱',
  'portugal': '🇵🇹',
  'qatar': '🇶🇦',
  'romania': '🇷🇴',
  'russia': '🇷🇺',
  'saudi-arabia': '🇸🇦',
  'singapore': '🇸🇬',
  'slovakia': '🇸🇰',
  'slovenia': '🇸🇮',
  'south-africa': '🇿🇦',
  'spain': '🇪🇸',
  'sri-lanka': '🇱🇰',
  'sudan': '🇸🇩',
  'sweden': '🇸🇪',
  'switzerland': '🇨🇭',
  'syria': '🇸🇾',
  'taiwan': '🇹🇼',
  'thailand': '🇹🇭',
  'tunisia': '🇹🇳',
  'turkey': '🇹🇷',
  'ukraine': '🇺🇦',
  'united-arab-emirates': '🇦🇪',
  'united-kingdom': '🇬🇧',
  'united-states': '🇺🇸',
  'uzbekistan': '🇺🇿',
  'venezuela': '🇻🇪',
  'vietnam': '🇻🇳',
  'yemen': '🇾🇪',
  'zimbabwe': '🇿🇼',
  'other': '🌍'
}

/**
 * Get flag emoji for a country
 */
export function getCountryFlag(country: string): string {
  const normalizedCountry = country.toLowerCase().replace(/\s+/g, '-')
  return COUNTRY_FLAGS[normalizedCountry] || '🌍'
}

/**
 * Get country display name
 */
export function getCountryDisplayName(country: string): string {
  const displayNames: Record<string, string> = {
    'afghanistan': 'Afghanistan',
    'albania': 'Albania',
    'algeria': 'Algeria',
    'argentina': 'Argentina',
    'armenia': 'Armenia',
    'australia': 'Australia',
    'austria': 'Austria',
    'azerbaijan': 'Azerbaijan',
    'bangladesh': 'Bangladesh',
    'belarus': 'Belarus',
    'belgium': 'Belgium',
    'brazil': 'Brazil',
    'bulgaria': 'Bulgaria',
    'cambodia': 'Cambodia',
    'canada': 'Canada',
    'chile': 'Chile',
    'china': 'China',
    'colombia': 'Colombia',
    'croatia': 'Croatia',
    'czech-republic': 'Czech Republic',
    'denmark': 'Denmark',
    'egypt': 'Egypt',
    'estonia': 'Estonia',
    'finland': 'Finland',
    'france': 'France',
    'georgia': 'Georgia',
    'germany': 'Germany',
    'ghana': 'Ghana',
    'greece': 'Greece',
    'hungary': 'Hungary',
    'iceland': 'Iceland',
    'india': 'India',
    'indonesia': 'Indonesia',
    'iran': 'Iran',
    'iraq': 'Iraq',
    'ireland': 'Ireland',
    'israel': 'Israel',
    'italy': 'Italy',
    'japan': 'Japan',
    'jordan': 'Jordan',
    'kazakhstan': 'Kazakhstan',
    'kenya': 'Kenya',
    'south-korea': 'South Korea',
    'kuwait': 'Kuwait',
    'latvia': 'Latvia',
    'lebanon': 'Lebanon',
    'lithuania': 'Lithuania',
    'luxembourg': 'Luxembourg',
    'malaysia': 'Malaysia',
    'mexico': 'Mexico',
    'moldova': 'Moldova',
    'mongolia': 'Mongolia',
    'morocco': 'Morocco',
    'myanmar': 'Myanmar',
    'nepal': 'Nepal',
    'netherlands': 'Netherlands',
    'new-zealand': 'New Zealand',
    'nigeria': 'Nigeria',
    'north-korea': 'North Korea',
    'norway': 'Norway',
    'pakistan': 'Pakistan',
    'peru': 'Peru',
    'philippines': 'Philippines',
    'poland': 'Poland',
    'portugal': 'Portugal',
    'qatar': 'Qatar',
    'romania': 'Romania',
    'russia': 'Russia',
    'saudi-arabia': 'Saudi Arabia',
    'singapore': 'Singapore',
    'slovakia': 'Slovakia',
    'slovenia': 'Slovenia',
    'south-africa': 'South Africa',
    'spain': 'Spain',
    'sri-lanka': 'Sri Lanka',
    'sudan': 'Sudan',
    'sweden': 'Sweden',
    'switzerland': 'Switzerland',
    'syria': 'Syria',
    'taiwan': 'Taiwan',
    'thailand': 'Thailand',
    'tunisia': 'Tunisia',
    'turkey': 'Turkey',
    'ukraine': 'Ukraine',
    'united-arab-emirates': 'United Arab Emirates',
    'united-kingdom': 'United Kingdom',
    'united-states': 'United States',
    'uzbekistan': 'Uzbekistan',
    'venezuela': 'Venezuela',
    'vietnam': 'Vietnam',
    'yemen': 'Yemen',
    'zimbabwe': 'Zimbabwe',
    'other': 'Other'
  }

  const normalizedCountry = country.toLowerCase().replace(/\s+/g, '-')
  return displayNames[normalizedCountry] || country
}

/**
 * Get all countries for filter dropdown
 * Returns array of { value, label, flag } objects
 */
export function getAllCountries() {
  return Object.keys(COUNTRY_FLAGS)
    .filter(key => key !== 'other')
    .map(key => ({
      value: key,
      label: getCountryDisplayName(key),
      flag: COUNTRY_FLAGS[key]
    }))
    .sort((a, b) => a.label.localeCompare(b.label))
}
