'use client' import { useState } from 'react'
import { auth } from '@/lib/firebase/client'
import { verifyBeforeUpdateEmail } from 'firebase/auth'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle,
} from '@/components/ui/dialog'
import { Mail } from 'lucide-react'
import { InlineSpinner } from '@/components/ui/loading' /** * Props for the change email modal */
interface ChangeEmailModalProps { isOpen: boolean onClose: () => void currentEmail: string
} /** * Modal component for changing user email */
export function ChangeEmailModal({ isOpen, onClose, currentEmail }: ChangeEmailModalProps) { const [newEmail, setNewEmail] = useState('') const [isLoading, setIsLoading] = useState(false) const [error, setError] = useState<string | null>(null) const [success, setSuccess] = useState(false) const handleSubmit = async (e: React.FormEvent) => { e.preventDefault() setError(null) setIsLoading(true) // Validation if (newEmail === currentEmail) { setError('New email must be different from current email') setIsLoading(false) return } const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/ if (!emailRegex.test(newEmail)) { setError('Please enter a valid email address') setIsLoading(false) return } try { const user = auth.currentUser if (!user) throw new Error('User not found') await verifyBeforeUpdateEmail(user, newEmail) setSuccess(true) setNewEmail('') // Close modal after a short delay setTimeout(() => { onClose() setSuccess(false) }, 3000) } catch (error: unknown) { setError(error instanceof Error ? error.message : 'Failed to update email') } finally { setIsLoading(false) } } const handleClose = () => { if (!isLoading) { setError(null) setSuccess(false) setNewEmail('') onClose() } } return ( <Dialog open={isOpen} onOpenChange={handleClose}> <DialogContent className="sm:max-w-md"> <DialogHeader> <DialogTitle>Change Email Address</DialogTitle> <DialogDescription> Enter your new email address. You&apos;ll receive a confirmation email to verify the change. </DialogDescription> </DialogHeader> {success ? ( <div className="text-center py-4 space-y-3"> <div className="w-12 h-12 bg-success/15 rounded-none flex items-center justify-center mx-auto"> <Mail className="w-6 h-6 text-success"/> </div> <div className="text-success">Email update initiated!</div> <div className="text-sm text-muted-foreground"> Please check your new email address for a confirmation link. </div> </div> ) : ( <form onSubmit={handleSubmit} className="space-y-4"> <div className="space-y-2"> <Label htmlFor="current-email">Current Email</Label> <Input id="current-email"type="email"value={currentEmail} disabled className="bg-muted"/> </div> <div className="space-y-2"> <Label htmlFor="new-email">New Email Address</Label> <Input id="new-email"type="email"value={newEmail} onChange={(e) => setNewEmail(e.target.value)} placeholder="Enter new email address"required disabled={isLoading} /> </div> {error && ( <div className="text-sm text-error-foreground bg-error p-3 rounded-none"> {error} </div> )} <DialogFooter> <Button type="button"variant="outline"onClick={handleClose} disabled={isLoading}> Cancel </Button> <Button type="submit"disabled={isLoading}> {isLoading && <InlineSpinner className="mr-2"/>} Update Email </Button> </DialogFooter> </form> )} </DialogContent> </Dialog> )
}
